# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from imageBPCS import imageBPCS
from imageLSB import imageLSB
from aviVideo import AviVideo
from audio import Audio, audio_psnr

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.stego = Audio()
        self.stego_list = [
            imageLSB(),
            imageBPCS(),
            AviVideo(),
            Audio()
        ]

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.choose_stego_dropdown = QtWidgets.QComboBox(self.header_frame)
        self.choose_stego_dropdown.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.choose_stego_dropdown.setFont(font)
        self.choose_stego_dropdown.setObjectName("choose_stego_dropdown")
        self.choose_stego_dropdown.addItem("")
        self.choose_stego_dropdown.addItem("")
        self.choose_stego_dropdown.addItem("")
        self.choose_stego_dropdown.addItem("")
        self.horizontalLayout_3.addWidget(self.choose_stego_dropdown)
        self.open_media_button = QtWidgets.QPushButton(self.header_frame)
        self.open_media_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.open_media_button.setFont(font)
        self.open_media_button.setObjectName("open_media_button")
        self.horizontalLayout_3.addWidget(self.open_media_button)
        self.verticalLayout_5.addWidget(self.header_frame)

        ### MULAI IMAGE LSB
        self.option_frame = QtWidgets.QFrame(self.centralwidget)
        self.option_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.option_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.option_frame.setObjectName("option_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.option_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.image_lsb_widget = QtWidgets.QWidget(self.option_frame)
        self.image_lsb_widget.setObjectName("image_lsb_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.image_lsb_widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.image_lsb_widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.encryption_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.encryption_checkbox.setObjectName("encryption_checkbox")
        self.verticalLayout_2.addWidget(self.encryption_checkbox)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.randomized_checkbox = QtWidgets.QCheckBox(self.groupBox_3)
        self.randomized_checkbox.setObjectName("randomized_checkbox")
        self.verticalLayout_4.addWidget(self.randomized_checkbox)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_6.addWidget(self.widget)
        self.groupBox_4 = QtWidgets.QGroupBox(self.image_lsb_widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.key_input_text = QtWidgets.QLineEdit(self.groupBox_4)
        self.key_input_text.setObjectName("key_input_text")
        self.horizontalLayout_2.addWidget(self.key_input_text)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.horizontalLayout_4.addWidget(self.image_lsb_widget)
        ### SELESAI IMAGE LSB ###
        self.verticalLayout_5.addWidget(self.option_frame)
        self.footer_frame = QtWidgets.QFrame(self.centralwidget)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.footer_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.footer_frame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.embeed_button = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.embeed_button.setFont(font)
        self.embeed_button.setObjectName("embeed_button")
        self.horizontalLayout_6.addWidget(self.embeed_button)
        self.extract_button = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.extract_button.setFont(font)
        self.extract_button.setObjectName("extract_button")
        self.horizontalLayout_6.addWidget(self.extract_button)
        self.verticalLayout.addWidget(self.widget_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.footer_frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.open_initial_button = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.open_initial_button.setFont(font)
        self.open_initial_button.setObjectName("open_initial_button")
        self.horizontalLayout_8.addWidget(self.open_initial_button)
        self.open_result_button = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.open_result_button.setFont(font)
        self.open_result_button.setObjectName("open_result_button")
        self.horizontalLayout_8.addWidget(self.open_result_button)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.info_text = QtWidgets.QPlainTextEdit(self.footer_frame)
        self.info_text.setObjectName("info_text")
        self.verticalLayout.addWidget(self.info_text)
        self.verticalLayout_5.addWidget(self.footer_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuStegonya_Meyer = QtWidgets.QMenu(self.menubar)
        self.menuStegonya_Meyer.setObjectName("menuStegonya_Meyer")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuStegonya_Meyer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.choose_stego_dropdown.currentIndexChanged.connect(self.change_stego)

        self.stego.render(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_stego_dropdown.setItemText(0, _translate("MainWindow", "Image (LSB)"))
        self.choose_stego_dropdown.setItemText(1, _translate("MainWindow", "Image (BPCS)"))
        self.choose_stego_dropdown.setItemText(2, _translate("MainWindow", "Video"))
        self.choose_stego_dropdown.setItemText(3, _translate("MainWindow", "Audio"))
        self.open_media_button.setText(_translate("MainWindow", "Open Media File"))
        self.groupBox.setTitle(_translate("MainWindow", "Encryption"))
        self.encryption_checkbox.setText(_translate("MainWindow", "Enable"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Random"))
        self.randomized_checkbox.setText(_translate("MainWindow", "Randomized Pixel"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Key"))
        self.embeed_button.setText(_translate("MainWindow", "Embeed"))
        self.extract_button.setText(_translate("MainWindow", "Extract"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Open Media Viewer/Player"))
        self.open_initial_button.setText(_translate("MainWindow", "Initial"))
        self.open_result_button.setText(_translate("MainWindow", "Result"))
        self.menuStegonya_Meyer.setTitle(_translate("MainWindow", "Stegonya Meyer"))

    def clean(self, layout):
        for i in reversed(range(layout.count())):
            item = layout.takeAt(i)
            widget = item.widget()
            if widget is not None:
                widget.close()
            else:
                self.clean(item.layout())
    
    def change_stego(self, idx:int):
        self.clean(self.verticalLayout_5)
        self.stego = self.stego_list[idx]

        self.option_frame = QtWidgets.QFrame(self.centralwidget)
        self.option_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.option_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.option_frame.setObjectName("option_frame")
        self.stego.render(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
